### ISSUE TITLE
support nested types in inline syntax

### ISSUE THREAD

**Issue by swachter** [non/kind-projector#56]
Translate Future[List[?]] into "type X[a] = Future[List[a]]", i.e. consider nested type constructors.

**Comment by non** [comment]
@swachter I think this ends up being syntactically ambiguous (i.e. without knowing anything about the types, you can't predict which version will "work").

For example:

```scala
trait Functor[F[_]]

Functor[Either[Unit, ?]]
// Functor[({type X[a] = Either[Unit, a]})#X]

Future[Either[Unit, ?]]
// {(type X[a] = Future[Either[Unit, a]]})#X
```

I'm reluctant to support some kind of "fallback" behavior because I think that would make reading type lambdas *more* confusing (there will still be cases where the `Lambda[a => ...]` syntax is required).

**Comment by swachter** [comment]
@non Yes, you are right, it would be ambiguous. I would suggest to always bind the innermost type, i.e. have the enclosing type constructors unchanged. This seems to me most natural.

**Comment by TomasMikula** [comment]
That's how it works now, isn't it?

**Comment by swachter** [comment]
No, quote from README.md: "Future[List[?]] is invalid"

**Comment by TomasMikula** [comment]
Right, it is invalid because `?` is bound by the innermost type constructor (`List`), as you seemed to be suggesting in your previous comment.

**Comment by ritschwumm** [comment]
better keep it in sync with values in scala

**Comment by TomasMikula** [comment]
What do you mean?

On Dec 1, 2017 7:43 PM, "ritschwumm" <notifications@github.com> wrote:

better keep it in sync with values in scala

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/non/kind-projector/issues/56#issuecomment-348575246>,
or mute the thread

**Comment by ritschwumm** [comment]
@TomasMikula foo(bar(_)) in

**Comment by TomasMikula** [comment]
Agreed. This is how it works in kind-projector.

```scala
Future[List[?]]
```

is equivalent to

```scala
Future[λ[X => List[X]]]
```

and it doesn't work because `Future` requires a type, not a type constructor.

**Comment by non** [comment]
Alright with folks if I close this? (Please comment if you'd like me to leave it open.)

**Comment by non** [comment]
It's been 18 days since I asked about closing, so closing now.
