### ISSUE TITLE
Change ? to another symbol

### ISSUE THREAD

**Issue by nightscape** [non/kind-projector#84]
It seems like Dotty will get native type lambdas. The plan there is to use `F[_]` as a short-hand syntax for the type lambda `[X] => F[X]` and `F[?]` to be the wildcard syntax which unfortunately is different to how the `?` is used in kind-projector.
In https://github.com/lampepfl/dotty/issues/5379 there's a discussion of doing the swap incrementally in Scala 3.0 - 3.3, but imo that would lead to unnecessary churn and confusion, so I was wondering if kind-projector could preemptively replace the `?` by another symbol so that until Dotty is out the `?` is free to use for wildcards.
Maintainers' opinions are welcome here or in the above ticket 😃

**Comment by TomasMikula** [comment]
Thank you for letting us know! I think the proposed syntax (`F[?]` for existential, `F[_]` for `[X] => F[X]`) is more intuitive. It will probably be a long and painful transition for projects, but I view it positively overall.

The question for kind projector is, what symbol do we use (alongside `?`) in shorthand syntax for type lambdas.

In math, `–` (en-dash) is commonly used for this purpose, as in

> Hom(A,–) maps each object X in C to the set of morphisms, Hom(A, X).

The problem is that the en-dash is not a valid Scala identifier. Also, it is not easily typed on a keyboard.

So I suggest to use `--` (double minus), which is also the TeX way to typeset an en-dash.

**Comment by LukaJCB** [comment]
How about using a star `*`? I'm not sure if double minus is a great idea, since a single minus already means contravariance. 

I think something like `Either[Error, *]` reads relatively nice.

**Comment by kubukoz** [comment]
Let's rename to `∃` :D 

/s `*` sounds like a good idea

**Comment by TomasMikula** [comment]
See #91 where I went with `*`.
